# Generated by Django 5.1.7 on 2025-04-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_soil_moisture', models.FloatField()),
                ('max_soil_moisture', models.FloatField()),
                ('min_ec', models.FloatField()),
                ('max_ec', models.FloatField()),
                ('fertilizer_ratio', models.FloatField()),
                ('min_humidity', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'standard_data',
            },
        ),
    ]
