# Generated by Django 5.1.7 on 2025-04-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standarddata',
            old_name='min_temperature',
            new_name='max_temperature',
        ),
    ]
