# Generated by Django 5.1.7 on 2025-04-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard_data', '0002_rename_min_temperature_standarddata_max_temperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standarddata',
            options={'get_latest_by': 'created_at'},
        ),
    ]
