# Generated by Django 5.1.7 on 2025-03-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField()),
                ('soil_temperature', models.FloatField()),
                ('ec', models.FloatField()),
                ('soil_nitrogen', models.FloatField()),
                ('soil_phosphorus', models.FloatField()),
                ('soil_potassium', models.FloatField()),
                ('ph', models.FloatField()),
                ('co2', models.FloatField()),
                ('temp_air', models.FloatField()),
                ('hum_air', models.FloatField()),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
