# Generated by Django 5.1.7 on 2025-03-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
