# Generated by Django 5.1.7 on 2025-04-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_rename_time_stamp_sensordata_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensordata',
            table='sensor_data',
        ),
    ]
