# Generated by Django 5.1.7 on 2025-04-02 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0003_alter_sensordata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensordata',
            table='sensors_data',
        ),
    ]
