# Generated by Django 5.1.7 on 2025-04-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0004_alter_sensordata_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'get_latest_by': 'created_at'},
        ),
    ]
