# Generated by Django 5.1.7 on 2025-05-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0006_nutrientalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrientalert',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
