# Generated by Django 5.1.7 on 2025-05-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0007_alter_nutrientalert_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrientalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
